### ISSUE TITLE
View project solution folder structure

### ISSUE THREAD

**Issue by ShivamMukherjee** [kleber-swf/vscode-unity-code-snippets#10]
@kleber-swf How should I enable the Visual Studio solution folder structure as shown in the GIFs in your README? Currently, I use `fernandoescolar.vscode-solution-explorer` (vscode-solution-explorer) for this.

**Comment by kleber-swf** [comment]
Hey there.

Well... I don't know if I understood your question, but I think that is the default folder structure presentation on VSCode. I have two visual extensions installed though: [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) and [Base16 Ocean Dark Extended Theme](https://marketplace.visualstudio.com/items?itemName=kleber-swf.ocean-dark-extended).
