### ISSUE TITLE
Remove/Disable snippets

### ISSUE THREAD

**Issue by LaCreArthur** [kleber-swf/vscode-unity-code-snippets#12]
I'd like to disable snippets that are more annoying than anything, 
for instance the "OnParticleCollision(GameObject)" appears every time you tape "private ga" (for private GameObject obviously) and it has priority over intellisense so you can't arrow down to choose "GameObject", forcing you to tape the whole word or escape the suggestion. 

So that's why it would be great to be able to disable some snippets. Thanks

**Comment by kleber-swf** [comment]
I think this is kinda related to this issue: https://github.com/kleber-swf/vscode-unity-code-snippets/issues/11

Basically you can alter the order intellisense shows its suggestions to fix it.
