### ISSUE TITLE
Singleton Snippet

### ISSUE THREAD

**Issue by Kzpryw** [kleber-swf/vscode-unity-code-snippets#13]
Hi, first of all thank you for your work :) it is very usefull :)

I would like to propose adding snippet for singletong, example code:

```
using UnityEngine;

public class GameManager : MonoBehaviour
{

    static GameManager instance;

    public static GameManager Instance
    {
        get
        {
            if (instance == null)
            {
                instance = GameObject.FindObjectOfType<GameManager>();
                if (instance == null)
                {
                    instance = new GameObject().AddComponent<GameManager>();
                }
            }
            return instance;
        }
    }

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
        else
        {
            Destroy(gameObject);
        }
    }
}
```

**Comment by kleber-swf** [comment]
Hi there!

OMG! Singletons are so much controversial (these days)[https://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons] hahha

But really, this is not in the scope of the engine itself. But don't be sad, you can easily create your own snippet: https://code.visualstudio.com/docs/editor/userdefinedsnippets
