### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by buger404** [kleber-swf/vscode-unity-code-snippets#18]
The editor told me the namespace **"UnityEngine.UI" was missing** .
But I can run my code successfully in Unity .

//////Environment////////////////////////////////////////////////////////////////
Unity Version : 2019.3
VSCode : 1.41.3
////////////////////////////////////////////////////////////////////////////////////

**Reinstall the extension : the problem is still not solved .
Reinstall VS Code : the problem is still not solved .
Reinstall Unity : the problem is still not solved .**

**Comment by Diegw** [comment]
I have just fix this problem for myself. Its not this extension

Just go to Window - Package Manager - Visual Studio Code and change your version to 1.1.3
Close Unity
Delete Assembly-CSharp.csproj and (ProjectName).sln from your project folder
Open Unity and your project again and you should now be able to use UnityEngine.UI

**Comment by buger404** [comment]
Thanks for your replying , it works !
