### ISSUE TITLE
Gizmos not been suggested

### ISSUE THREAD

**Issue by MrAmericanMike** [kleber-swf/vscode-unity-code-snippets#19]
So I was writing some code and found out that Gizmos by itself wasn't been suggested.

https://imgur.com/ErT6g9f

Do I need to modify something so Gizmos is suggested, or it's just not implemented yet?

I wonder if something "broke" for the auto-completion, after installing it suggested "gameObject" but not that's not the case.

Is there a way to check what could be wrong?

**Comment by kleber-swf** [comment]
`gizmos` is something coming from Unity intellisense. Can you please check if it's still happening?
