### ISSUE TITLE
Check existing text on line

### ISSUE THREAD

**Issue by spherous** [kleber-swf/vscode-unity-code-snippets#23]
Great tool btw, tons of really useful features!

It just frustrates me when I type "private void Up" then press tab to complete and end up getting this:

private void private void Update() {
        
}

I know that if I just typed "Up" and pressed tab I'd get what I want, but force of habit for writing I methods gets me often typing the scope and return type before the name.

**Comment by kleber-swf** [comment]
I'm afraid this is not possible with snippets. In the future I plan to make the `private` keyword optional. This will kinda fix this issue for you.
