### ISSUE TITLE
Publish extension on Open-VSX, so it can be used in VSCodium, Gitpod

### ISSUE THREAD

**Issue by geekley** [kleber-swf/vscode-unity-code-snippets#24]
Can you please publish the extension on [open-vsx.org](https://open-vsx.org), so it can reach more users?
Open-VSX is a vendor-neutral alternative to VS Marketplace, [that can legally be used](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) in VS Code forks like [VSCodium](https://github.com/VSCodium/vscodium#why-does-this-exist), [GitPod](https://www.gitpod.io/features/#vs).
Of course, you don't have to change anything in the extension itself.

[The process](https://github.com/eclipse/openvsx/blob/master/cli/README.md) is pretty much the same as publishing to VS Marketplace.
It can even be automated, see [this repo](https://github.com/open-vsx/publish-extensions#publish-extensions-to-open-vsx):
> Though the preferred solution for such a situation is to convince the maintainers to start publishing themselves, you can add the extensions here to have them published by our CI workflow.

You can [claim ownership](https://github.com/eclipse/openvsx/wiki/Namespace-Access) of your namespace `kleber-swf`, and officially support the extension there.

More details on [this blog post](https://www.gitpod.io/blog/open-vsx/).

**Comment by kleber-swf** [comment]
It's there!

**Comment by kleber-swf** [comment]
Just published: https://open-vsx.org/extension/kleber-swf/unity-code-snippets

**Comment by geekley** [comment]
It's being listed as "Provided License" instead of MIT License. I believe that may be because it's missing the license field on package.json. You might wanna add that for the next version.

**Comment by geekley** [comment]
ah nevermind
