### ISSUE TITLE
Add option to make open brackets in a new line

### ISSUE THREAD

**Issue by SunnyMonster123** [kleber-swf/vscode-unity-code-snippets#27]
Just like the title is saying, please add an option for open brackets in a new line. I personally like the open brackets being in a new line more, so it is a bit annoying having to manually put them in a new line. Please add this functionality! Thank you

**Comment by Cdddo** [comment]
> I just found a fork that does this, FYI:
> https://github.com/cemuka/vscode-unity-code-snippets

This fork is not being actively developed unfortunately, there's several mistakes already.
I'd make my own fork to fix the, but I don't know how to make VSC extensions yet.
It would be nicer to just have this extension have an option to use the new line style for those of us that prefer it.

**Comment by Serveladik** [comment]
PLEASE!!!!

**Comment by Cdddo** [comment]
For anyone interested I finally took some time to learn and published my own fork with the new line style here
[](https://marketplace.visualstudio.com/items?itemName=Cdddo.unity-code-snippets-newline). I intend to keep this up to date. 😀

Repo is https://github.com/Cdddo/vscode-unity-code-snippets

**Comment by Cvnvr** [comment]
@Cdddo is there a way to stop the methods in your fork from generating summary comments with every method? it doesn't in the original version - ideally all i want is the exact same behaviour in the original with just the opening brackets placed on a new line

**Comment by chelloiaco** [comment]
@Cvnvr just open up your ` %USERPROFILE%\.vscode\extensions\kleber-swf.unity-code-snippets-1.3.0\snippets` and edit the snippets.json, save and reload VSCode

**Comment by kleber-swf** [comment]
Version 2.0.0 is live and now it has the option to change to Allman indentation style (open brackets in a new line)!
I hope it's not too late :sweat_smile:

**Comment by kleber-swf** [comment]
Hi, @ZayNepz . Sorry about that.
Can you please describe this issue with more details, so I can try to fix it?
Thanks

**Comment by cuir0929** [comment]
I know why !  I dont open format on type！ sorry，ignore me
I'm also experiencing this issue. After switching to the Allman style in the settings and restarting VS Code, the curly braces still remain on the same line as the method names instead of automatically moving to a new line.
