### ISSUE TITLE
Just some more suggestions

### ISSUE THREAD

**Issue by 00shahaf** [kleber-swf/vscode-unity-code-snippets#3]
the library is still pretty small and doesn't cover many methods that Unity users use. I would have gladly help you expand it, but I'm still a big dummy with code

**Comment by kleber-swf** [comment]
Hi there!
Did you have a list of suggestions?
I can put them into the extension in no time 😄 
(Sorry for the delay, I had no notification)

**Comment by 00shahaf** [comment]
Actually i have no idea what this is about  :)

**Comment by kleber-swf** [comment]
😄 no problem. I'm closing the issue then.
