### ISSUE TITLE
Singleton shortcut.

### ISSUE THREAD

**Issue by akbalburak** [kleber-swf/vscode-unity-code-snippets#30]
Hi, i have started using plugin just now. I wonder is there a short cut to create a singleton?

**Comment by kleber-swf** [comment]
Singleton is not exactly a Unity feature. It's more like a Design Pattern (a controversial one).
The intention of this extension is just provide snippets for Unity features.
But you can add a snippet yourself using VSCode custom snippet configurations: https://code.visualstudio.com/docs/editor/userdefinedsnippets
