### ISSUE TITLE
Error -1703

### ISSUE THREAD

**Issue by eveciana21** [kleber-swf/vscode-unity-code-snippets#35]
My visual studio code was working perfectly earlier today, but now I am getting an error message when trying to open visual studio code by clicking on the script within Unity. I am capable of opening it directly via the visual studio code shortcut, but not within unity by clicking on the VS Code script. The error message reads "The application “Visual Studio Code” can’t be opened.-1703". Please Help

**Comment by MizuRyujin** [comment]
This might not be the best place to ask those question, since it's not related to the repo itself, but either way, check if Unity's preferences -> External tools is set up correctly and in the package manager the VSCode package is up-to-date
