### ISSUE TITLE
Suggestion: allow to remove the 'private' access modifier

### ISSUE THREAD

**Issue by Jihaysse** [kleber-swf/vscode-unity-code-snippets#39]

**Comment by Aincvy** [comment]
In class inheritance, if subclass has a same message with base class, then subclass method will be invoked, base class methods are invalid, and no any tips in vs-code-editor.

**Comment by kleber-swf** [comment]
This won't be easy, but if it has enough upvotes I can make it.

**Comment by kleber-swf** [comment]
Never mind. It wasn't that hard. Added the option to remove the `private` accessor keywork on version `2.1.0`
