### ISSUE TITLE
Change Bracket Formatting Setting

### ISSUE THREAD

**Issue by JasonAvis** [kleber-swf/vscode-unity-code-snippets#4]
Is there a setting for the extension that I could change how the snippets put brackets on the same line? I personally prefer having the brackets on their own line so using this extension requires me to go back and fix it every time I put in a snippet. I know others prefer brackets on the same line so just a setting to change that depending on preferences I feel would be helpful.

**Comment by kleber-swf** [comment]
The VSCode snippet doesn't have the option to handle formatting. Maybe you can put an [omnisharp.json](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options) file and let it format your files with a shortcut (it seems to be `alt+shif+f` by default). Here is a blog post about it: [C# code formatting settings in VS Code and OmniSharp](https://www.strathweb.com/2017/01/c-code-formatting-settings-in-vs-code-and-omnisharp/)

I personally use this approach to format any code that is not right for my eyes :smile:.
