### ISSUE TITLE
SerializeField snippet

### ISSUE THREAD

**Issue by asatrain** [kleber-swf/vscode-unity-code-snippets#44]
Hello, can you please add a separate snippet for SerializeField to avoid conflict with default C# SerializeField snippet? Because right now it is needed to press two times an arrow key to select the right snippet.

![image](https://github.com/kleber-swf/vscode-unity-code-snippets/assets/58138008/a759cec1-f0c3-4422-aa10-36fae1e2313c)

I would suggest "sfield" like in Rider.

**Comment by kleber-swf** [comment]
Fixed on version `2.3.0`. Thanks for the suggestion.
