### ISSUE TITLE
Autocomplete code snippets not working as intended

### ISSUE THREAD

**Issue by chadstitch** [kleber-swf/vscode-unity-code-snippets#5]
Hey there first off, thanks for the code snippets!

However, I think there's a minor issue, but I'm not sure even sure if or how it's possible!

For example, if you type in "**private void**" and start typing OnCollision, or any method etc, the autocomplete will become "private void private void OnCollision" etc. 

And whatever you wrote before will stay. 

Do you think it's possible that it can parse to see if there's any text before and just parse what's necessary?

Thanks again for the snippets!

**Comment by kleber-swf** [comment]
Hey there!

Well... it can't be done because snippets are just "match this text, replace it with this other". You can try the built-in snippets for example, they work the same way.

Sorry about the delay. I don't receive any notifications (I'll try to fix it).
